Shopify adapters test
rubygarage/shopapp-shopify-android pull request #3
Opened 2018-03-12 08:49 UTC by starikovskii

2018-03-12 08:58 UTC, DenysZP approved these changes

2018-03-12 09:22 UTC, plzen requested changes

2018-03-12 09:22 UTC, plzen commented on library/src/test/java/com/shopapp/shopify/api/adapter/CategoryAdapterTest.kt
> +class CategoryAdapterTest {
Add test for second condition in `collection.descriptionHtml ?: DEFAULT_STRING`

2018-03-12 09:22 UTC, plzen commented on library/src/test/java/com/shopapp/shopify/api/adapter/CheckoutAdapterTest.kt
> +class CheckoutAdapterTest {
Add tests for 

```
adaptee.shippingAddress?.let { AddressAdapter.adapt(it) },
adaptee.shippingLine?.let { ShippingRateAdapter.adapt(it) }
```

2018-03-12 09:22 UTC, plzen commented on library/src/test/java/com/shopapp/shopify/api/adapter/CountryListAdapterTest.kt
> +class CountryListAdapterTest {
Add test for second condition in `countries?.map { CountryAdapter.adapt(it) } ?: listOf()`

2018-03-12 09:22 UTC, plzen commented on library/src/test/java/com/shopapp/shopify/api/adapter/ErrorAdapterTest.kt
> +class ErrorAdapterTest {
Add tests for

```
adaptee.firstOrNull()?.let { Error.NonCritical(it.message()) }
---
return adaptee?.let {
    it.message?.let { Error.NonCritical(it) }
}
---
adaptee.firstOrNull()?.let { Error.NonCritical(it.message) }
```

2018-03-12 09:22 UTC, plzen commented on library/src/test/java/com/shopapp/shopify/api/adapter/PolicyAdapterTest.kt
> +class PolicyAdapterTest {
Add test for second condition in `return if (adaptee != null) {`

2018-03-12 09:22 UTC, plzen commented on library/src/test/java/com/shopapp/shopify/api/adapter/ProductAdapterTest.kt
> +class ProductAdapterTest {
Add tests for

```
productAdaptee.variants.edges.mapNotNull { ProductVariantAdapter.adapt(it.node) }
---
return if (variantsList.size > 0) {
    val mappedList = variantsList.mapNotNull { it.node.price }
    Pair(mappedList.min() ?: DEFAULT_PRICE, mappedList.max() ?: DEFAULT_PRICE)
---
productAdaptee.images.edges.mapNotNull  { ImageAdapter.adapt(it.node)!! }
---
return if (options != null) {
```

2018-03-12 09:22 UTC, plzen commented on library/src/test/java/com/shopapp/shopify/api/adapter/StateListAdapterTest.kt
> +class StateListAdapterTest {
Add test for second condition in `states?.map { StateAdapter.adapt(it) } ?: listOf()`

2018-03-12 09:23 UTC, plzen requested changes
Also add tests for `ProductExtension.kt`

2018-03-13 10:29 UTC, plzen approved these changes

2018-03-16 12:06 UTC, merged